### ISSUE TITLE
Failed to install via pip

### ISSUE THREAD

**Issue by thimslugga** [dropbox/trapperkeeper#16]
(env) root@host:/opt/snmptraps# pip install trapperkeeper
Collecting trapperkeeper
  Using cached trapperkeeper-0.6.0.tar.gz
Collecting Jinja2==2.7.1 (from trapperkeeper)
  Downloading Jinja2-2.7.1.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 2.5MB/s 
Collecting MarkupSafe==0.18 (from trapperkeeper)
  Downloading MarkupSafe-0.18.tar.gz
Collecting MySQL-python==1.2.5 (from trapperkeeper)
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 7.2MB/s 
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gu4H2J/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gu4H2J/MySQL-python/

(env) root@host:/opt/snmptraps# pip install git+https://github.com/dropbox/trapperkeeper.git
Collecting git+https://github.com/dropbox/trapperkeeper.git
  Cloning https://github.com/dropbox/trapperkeeper.git to /tmp/pip-aGuCYn-build
Collecting Jinja2==2.7.1 (from trapperkeeper==0.6.0)
  Using cached Jinja2-2.7.1.tar.gz
Collecting MarkupSafe==0.18 (from trapperkeeper==0.6.0)
  Using cached MarkupSafe-0.18.tar.gz
Collecting MySQL-python==1.2.5 (from trapperkeeper==0.6.0)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_3y8cR/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_3y8cR/MySQL-python/

**Comment by gmjosack** [comment]
pretty sure `mysql_config` needs to be available on your system to install the `MySQL-python` package in general.

Not sure what distro you're running but assuming debian you'd want to make sure `libmysqlclient-dev` is installed.

**Comment by thimslugga** [comment]
This resolved the first issue.

> sudo apt-get install libmysqlclient-dev

Collecting distribute==0.6.49 (from trapperkeeper)
  Downloading distribute-0.6.49.zip (772kB)
    100% |████████████████████████████████| 778kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Jl3rmI/distribute/setup.py", line 232, in <module>
        scripts = scripts,
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "pkg_resources.py", line 2099, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "pkg_resources.py", line 2309, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2538, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2571, in _compute_dependencies
        common = frozenset(reqs_for_extra(None))
      File "pkg_resources.py", line 2568, in reqs_for_extra
        if req.marker_fn(override={'extra':extra}):
      File "_markerlib/markers.py", line 109, in marker_fn
        return eval(compiled_marker, environment)
      File "<environment marker>", line 1, in <module>
    NameError: name 'sys_platform' is not defined

**Comment by gmjosack** [comment]
If you're using virtualenv can you verify whether you're using an old version or not? I've seen this issue in the past with old versions of pip/setuptools/virtualenv. From outside the virtualenv can you run `virtualenv --version` and from inside can you provide `pip --version`?

**Comment by thimslugga** [comment]
root@host:/opt/snmptraps# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

root@host:/opt/snmptraps# virtualenv --version
15.1.0

root@host:/opt/snmptraps# pip install --upgrade setuptools
root@host:/opt/snmptraps# pip install --upgrade distribute

upgraded those packages above and also created a new virtualenv but stilling running into same issue.

**Comment by thimslugga** [comment]
I think I got it finally :+1: I created a pull request from fork with some tweaks.

**Comment by gmjosack** [comment]
This should be fixed with #17. Thanks!
