### ISSUE TITLE
Question: logging and reloading?

### ISSUE THREAD

**Issue by poblabs** [dropbox/trapperkeeper#18]
If I add a new trapHandler in trapperkeeper.yaml, do I have to restart the process (I'm assuming yes). 

Is there a way to log incoming traps to syslog?

Thanks again!

**Comment by jathanism** [comment]
Hi there. Short answer: Yes, you must restart the process for config changes to take effect.

There's no built-in way to log traps to syslog. For a simple solution where you're running `trapperkeeper` in the foreground in something like screen/tmux, you could send logs using the `logger` util. (See: `man 1 logger` on a Linux box)

You might also try looking at a process manager like `supervisord` which can send any stdout/stderr from the server process to syslog. (See: http://supervisord.org/logging.html)

**Comment by poblabs** [comment]
Thanks for the reply. I currently am running `trapperkeeper` on CentOS 6, so I have it called from a quick and dirty init.d script. Sometimes I notice that traps from the same machine don't come in to the database if they come in rapid succession, so I was looking for a way to see a log as to why that might be happening

**Comment by jathanism** [comment]
Uh oh. Hope you didn't find a bug. How many processes do you have enabled?

**Comment by poblabs** [comment]
When I run `trapperkeeper` in the foreground, at times I do get some error output, but the script never closes, so I just ignored it and moved on. Thought to myself, maybe the trap didn't have all the values trapperkeeper needed? I can see if I can replicate that again. 

The init.d script just simply calls `/usr/bin/trapperkeeper` and runs it in the background. `ps aux | grep trapperkeeper` only shows 1 running, and I don't see anything on the yaml config to run multiples.

**Comment by jathanism** [comment]
My apologies. I was mixing up the processes. Disregard!

**Comment by poblabs** [comment]
No problem. Let me see if I'm able to replicate something.

**Comment by jathanism** [comment]
Pro tip: Crank up logging verbosity if you haven't already (`-v 3`)

**Comment by poblabs** [comment]
Maybe I'm going crazy - it is late on a Friday afterall, and I'm not about to claim SNMP is my strong suit, but the error I'm getting now when running it in the foreground looks to be SMTP related. I don't have the SMTP configured in `trapperkeeper` because I'm hooking it into Nagios instead. 

```
SMTPSenderRefused: (553, '5.5.4 <trapperkeeper>... Domain name required for sender address trapperkeeper', 'trapperkeeper')
ERROR:root:Callback Failed: (553, '5.5.4 <trapperkeeper>... Domain name required for sender address trapperkeeper', 'trapperkeeper')
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/trapperkeeper/callbacks.py", line 39, in __call__
    self._call(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/trapperkeeper/callbacks.py", line 166, in _call
    self._send_mail(handler, trap, duplicate)
  File "/usr/lib/python2.6/site-packages/trapperkeeper/callbacks.py", line 68, in _send_mail
    subject, self.template_env, ctxt)
  File "/usr/lib/python2.6/site-packages/trapperkeeper/utils.py", line 127, in send_trap_email
    smtp.sendmail(sender, recipients, msg.as_string())
  File "/usr/lib64/python2.6/smtplib.py", line 710, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (553, '5.5.4 <trapperkeeper>... Domain name required for sender address trapperkeeper', 'trapperkeeper')
```

Running an `snmptrap` command in rapid succession showed all being saved to the database. 

Hmm. Guess I'll keep my eye out :)

**Comment by jathanism** [comment]
If it makes you feel any better, SNMP is not anyone's strong suit. 💣

**Comment by poblabs** [comment]
Makes me wonder why the first word in the acronym is `simple` :thinking:

**Comment by poblabs** [comment]
Closing for now. Thanks for answering the questions. Will report back if I find anything further! Thanks again
