### ISSUE TITLE
want display notification is text format not in oid format

### ISSUE THREAD

**Issue by jeffery9** [dropbox/trapperkeeper#8]
the trap is displayed in oid format, this is not friendly.
![image](https://cloud.githubusercontent.com/assets/1404460/9898307/ccbfb8da-5c83-11e5-9c1f-e566c4582201.png)

how can i let it display in text format?

and another feature asked is that the web page can dynamic updated and play a sound when trapperkeeper received the trap.

any feedback should be thanksful

**Comment by gmjosack** [comment]
TrapperKeeper uses the default mibs via netsnmp. You can see the default path for your system by running `net-snmp-config --default-mibdirs`. You can use the following environment variables usually documented in the `snmpcmd` man page

> MIBS - The list of MIBs to load. Defaults to SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:SNMP-VACM-MIB.

> MIBDIRS - The list of directories to search for MIBs. Defaults to /usr/share/snmp/mibs.

For example I run TrapperKeeper with the following environment to add a directory to the path and load all mibs.

`MIBS=ALL MIBDIRS=+/usr/share/mibs/local/`

I've updated the README with this info. Thanks for the report!

I doubt I'll add an audio notification for new traps as that would be excessive during large events though I have entertained the idea of adding auto reload. I'm going to close this issue. If you want to track dynamic updates separately feel free to open another issue for it.
